# Generated by Django 3.1.7 on 2021-03-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0002_auto_20210309_0526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPlatform',
        ),
    ]
