# Generated by Django 3.1.7 on 2021-03-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0003_delete_userplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
