# Generated by Django 3.1.7 on 2021-03-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0004_live_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
